### ISSUE TITLE
How to prepare the data please?

### ISSUE THREAD

**Issue by ShaneeyS** [kdwonn/DivE#3] opened 2023-09-24 07:24 UTC
Hi, when I try to run the code and reproduce the results of your paper, several issuses arise:

1. When I just follow this [issue](https://github.com/kdwonn/DivE/issues/1) to run `python vocab.py --from_json ./vocab/coco_precomp_vocab.json`, it will generate a `coco_vocab.pkl`. However, how could I generate `coco_butd_vocab.pkl`? Are they the same? What is difference of `coco` and `coco_butd`?
2. When I rename `coco_vocab.pkl` to `coco_butd_vocab.pkl` and run the code, it raises an error: `No such file or directory: data/coco/annotations/coco_train_ids.npy`. How to generate `coco_train_ids.npy`?

Thanks in advance. Look forward to your reply.

**Comment by kdwonn** [comment] 2023-09-25 12:13
Hello! I appreciate your interest in our work.

1. I discovered that the previous reply for the vocab file generation was misleading. The vocabulary files are now contained in the repository. You can find them in [here](https://github.com/kdwonn/DivE/tree/8ebb9a802ec160a9d4e4bf7c552feff56a3de4e5/vocab) without generating them manually.
2. Datasets with `_butd` contain precomputed features obtained with Faster-RCNN instead of images. In other words, you need to use `coco_butd` for training the models with Faster-RCNN image backbone.
3. `coco_train_ids.npy` file is for the dataset split of the `coco` dataset and is provided together with the dataset itself. If you want to train the model with CNN backbones (which means that you want to use `coco`, not `coco_butd`), you can now download the dataset with [this script](https://github.com/kdwonn/DivE/blob/8ebb9a802ec160a9d4e4bf7c552feff56a3de4e5/data/coco_download.sh) (Actually, I forgot to include this script. Thank you for reminder!)

**Comment by ShaneeyS** [comment] 2023-09-30 14:00
Hi, Dongwon! Thanks a lot for your reply!

However, when I try to run the updated code with prepared datasets, it raises an error:

```
> /home/DivE-main/agg_block/attention.py(166)forward()
-> attn = self.attn_matrix_dropout(attn)
(Pdb) Traceback (most recent call last):
  File "train.py", line 410, in <module>
    main()
  File "train.py", line 368, in main
    loss, losses_dict, stat_dict = train(
  File "train.py", line 84, in train
    img_emb, txt_emb, img_sel_mask, txt_sel_mask, img_r, txt_r = model.forward(img, txt, img_len, txt_len)
  File "/home/DivE-main/model_spm.py", line 244, in forward
    img_emb, img_attn, img_residual = self.img_enc(images, img_len)
  File "/home/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/DivE-main/model_spm.py", line 676, in forward
    out, attn, residual = self.spm(
  File "/ehome/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/DivE-main/model_spm.py", line 185, in forward
    set_prediction = self.agg_block(local_feat, mask=pad_mask)
  File "/home/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/DivE-main/agg_block/agg_block.py", line 143, in forward
    x = cross_attn(x, context = data, mask = mask, k_pos = pos, q_pos = None) + x
  File "/home/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/DivE-main/agg_block/attention.py", line 47, in forward
    return self.fn(x, **kwargs)
  File "/home/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/DivE-main/agg_block/attention.py", line 166, in forward
    attn = self.attn_matrix_dropout(attn)
  File "/home/DivE-main/agg_block/attention.py", line 166, in forward
    attn = self.attn_matrix_dropout(attn)
  File "/home/anaconda3/envs/pytorch/lib/python3.8/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/home/anaconda3/envs/pytorch/lib/python3.8/bdb.py", line 112, in dispatch_line
    self.user_line(frame)
  File "/home/anaconda3/envs/pytorch/lib/python3.8/pdb.py", line 262, in user_line
    self.interaction(frame, None)
  File "/home/anaconda3/envs/pytorch/lib/python3.8/pdb.py", line 357, in interaction
    self._cmdloop()
  File "/home/anaconda3/envs/pytorch/lib/python3.8/pdb.py", line 322, in _cmdloop
    self.cmdloop()
  File "/home/anaconda3/envs/pytorch/lib/python3.8/cmd.py", line 126, in cmdloop
    line = input(self.prompt)
OSError: [Errno 9] Bad file descriptor

```

Could you please tell me how to solve the "Bad file descriptor" Error?

Thanks a lot!

**Comment by kdwonn** [comment] 2023-11-10 16:39
I'm sorry for not getting back to you sooner. I've taken a look, and it appears the issue might be specific to your system, as I haven't encountered similar issues in my searches.

I'll go ahead and close the issue for now. However, if it turns out the problem is tied to the code or something else on our end, don't hesitate to reach out. Thanks!

**Closed as completed by kdwonn** 2023-11-10 16:39 UTC
